---
- include: install_from_bin.yml
  when: marathon_install_mode == "bin"

- include: install_from_apt.yml
  when: marathon_install_mode == "apt"

- include: install_from_source.yml
  when: marathon_install_mode == "source"

- include: deploy.yml
  when: marathon_run_mode == "server"

- include: bridge.yml
  when: marathon_run_mode == "bridge" and discovery_method == "default"
