---
- hosts: all
  sudo: yes

  tasks:
    - name: Set global cluster variable facts
      set_fact:
        zk_endpoint: "zk://{{ groups['mesos-masters'] | join(':2181,') }}:2181"

    - name: Set global mesos variable facts
      set_fact:
        mesos_zk: "{{ zk_endpoint }}/mesos"

    - name: Set global marathon variable facts
      set_fact:
        marathon_host_servers: "{{ groups['mesos-masters'] }}"
        marathon_zk: "{{ zk_endpoint }}/marathon"

  roles:
    - common
    - cdh5-base

# Mesos masters
- hosts: mesos-masters
  gather_facts: false
  sudo: yes

  vars:
    - zookeeper_servers: "{{ groups['mesos-masters'] }}"
    - mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round(0, 'ceil') | int }}"

  roles:
    - { role: zookeeper, tags: [ 'zookeeper' ] }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: master }
    - { role: marathon, tags: [ 'marathon'] }
    #- { role: ansible-chronos, tags: [ 'chronos'] }

# Mesos slaves
- hosts: mesos-slaves
  gather_facts: false
  sudo: yes

  vars:
    - mesos_options_slave:
        containerizers: "docker,mesos"
        executor_registration_timeout: 5mins
    - zk_servers_noproto: "{{ groups['mesos-masters'] | join(':2181,') }}:2181"

  roles:
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: slave }
    - { role: marathon, tags: [ 'marathon'], marathon_run_mode: bridge }
    - { role: bamboo-haproxy, tags: [ 'bamboo'] }

# Kafka
- hosts: kafka-nodes
  gather_facts: false
  sudo: yes

  vars:
    - zk_servers_noproto: "{{ groups['mesos-masters'] | join(':2181,') }}:2181"
    - K_VERSION: 0.8.1.1
    - K_BUILD: kafka_2.9.2-{{K_VERSION}}
    - K_DATA_DIR: /var/data/kafka
    - Z_VERSION: 3.4.6
    - Z_BUILD: zookeeper-{{Z_VERSION}}
    - Z_DATA_DIR: /var/data/zookeeper

  roles:
    - { role: kafka, tags: [ 'kafka'], broker_id: 1 }

- hosts: cdh5-all
  roles:
  - cdh5-base
