---
- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - git
    - python-pip

- name: Display zk_server_noproto
  debug: msg="{{ zk_servers_noproto }}"

- name: install docker-py
  pip: name=docker-py version=0.3.1
# Build and prepare bamboo image
- name: Build bamboo image
  docker: image="thefactory/bamboo" command=-bind=":8000" name="bamboo" env="BAMBOO_ZK_HOST={{ zk_servers_noproto }}" ports="80:80,8000:8000"
  tags:
    - docker
    - docker_build

- name: Display IP address and port mappings for containers
  debug: msg="{{inventory_hostname}}:{{item['HostConfig']}}"
  with_items: docker_containers