---
- name: Get Docker release tool key
  apt_key: url="https://get.docker.io/gpg" state=present

- name: Add Docker deb repository
  apt_repository:
    repo="deb https://get.docker.io/ubuntu docker main" 
    state=present 
    update_cache=yes

- name: Install Docker
  apt: pkg=lxc-docker state=installed


